<?php
/**
 *
 * @author: flyrobin@foxmail.com
 * @date: 2017/7/2 002
 */

namespace app\controllers;


use yii\base\Controller;

class BaseApiController extends Controller
{
    public function actionIndex()
    {
        echo 11;
    }

    public function init()
    {
        $version = (float) \Yii::$app->getRequest()->headers->get('api-ver');
        $api_actions = "ApiV{$version}Controller/actions";
        //echo $api_actions; exit;
        \Yii::$app->runAction('ApiV2Controller/actionV2');
        exit;
    }

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
}