<?php

namespace app\controllers;
use app\models\Product;
use yii;
class ProductController extends yii\rest\ActiveController
{
    public $modelClass = 'app\models\Product';
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']);
        unset($actions['view']);
        return $actions;
    }

    public function actionIndex()
    {
        $Product = new Product();
        $num = Yii::$app->request->get('page', 2);
        $query = $Product::find();
        $total = $query->count();
        $Pagination = new yii\data\Pagination(['totalCount' => $total, 'defaultPageSize' => $num]);
        return [
            'code' => 'success',
            'total' => $total,
            'page' => Yii::$app->request->get('page', 1),
            'pages' => $Pagination->pageCount,
            'pagesize' => $Pagination->pageSize,
            'list' => $query->select(Yii::$app->request->get('fields', 'name,companyname'))->offset($Pagination->offset)->limit($Pagination->limit)->all()
        ];
    }

    public function actionView()
    {
        $Product = new Product();
        $id = Yii::$app->request->get('id', 0);
        $query = $Product::find();
        return [
            'code' => 'success',
            'id' => $id,
            'info' => $query->select(Yii::$app->request->get('fields', 'name,companyname'))->where(['id' => $id])->one()
        ];
    }
}
